language: generic
sudo: required
dist: trusty

env:
    global:
        - LOCAL_SWIFT_BRANCH="swift-4.0-release"
        - LOCAL_SWIFT_VERSION="swift-4.0-RELEASE"
    matrix:
        # Swift 4.0
        - CURL="7.55.1" HTTP2="v1.25.0" SWIFT_BRANCH="swift-4.0-release" SWIFT_VERSION="swift-4.0-RELEASE" TAG="aleksaubry/swift-apns:4.0"
        # Swift 4.0.2
        - CURL="7.56.1" HTTP2="v1.27.0" SWIFT_BRANCH="swift-4.0.2-release" SWIFT_VERSION="swift-4.0.2-RELEASE" TAG="aleksaubry/swift-apns:4.0.2"
        # Swift 4.0.3
        - CURL="7.57.0" HTTP2="v1.28.0" SWIFT_BRANCH="swift-4.0.3-release" SWIFT_VERSION="swift-4.0.3-RELEASE" TAG="aleksaubry/swift-apns:4.0.3"
        # Swift 4.1
        - CURL="7.59.0" HTTP2="v1.31.0" SWIFT_BRANCH="swift-4.1-release" SWIFT_VERSION="swift-4.1-RELEASE" TAG="aleksaubry/swift-apns:4.1"

install:
    - bash ./.ci/install.sh

script:
    - bash ./.ci/build.sh

deploy:
    provider: script
    script: bash ./.ci/release.sh
    skip_cleanup: true
    on:
        branch: release
