language: generic
sudo: required
dist: trusty
env:
    - CURL="7.54.0" HTTP2="v1.22.0" SWIFT="3.0.2"
    - CURL="7.54.0" HTTP2="v1.22.0" SWIFT="3.1.0"
    
install:
    - bash ./.ci/ssh.sh
    - bash ./.ci/install.sh
    
before_script:
    - export TAG=aleksaubry/swift-apns:$IMAGE_SWIFT
    
script:
    - docker-swift-apns --curl=$CURL --nghttp2=$HTTP2 --swift=$SWIFT --tag=$TAG