language: generic
sudo: required
dist: trusty

env:
    global:
        - LOCAL_SWIFT_BRANCH="swift-4.0-release"
        - LOCAL_SWIFT_VERSION="swift-4.0-RELEASE"
    matrix:
        # Swift 3.0.2
        - CURL="7.54.0" HTTP2="v1.22.0" SWIFT_BRANCH="swift-3.0.2-release" SWIFT_VERSION="swift-3.0.2-RELEASE" TAG="aleksaubry/swift-apns:3.0.2"
        # Swift 3.1
        - CURL="7.54.0" HTTP2="v1.22.0" SWIFT_BRANCH="swift-3.1-release" SWIFT_VERSION="swift-3.1-RELEASE" TAG="aleksaubry/swift-apns:3.1.0"
        # Swift 3.1.1
        - CURL="7.54.1" HTTP2="v1.24.0" SWIFT_BRANCH="swift-3.1.1-release" SWIFT_VERSION="swift-3.1.1-RELEASE" TAG="aleksaubry/swift-apns:3.1.1"
        # Swift 4.0
        - CURL="7.55.1" HTTP2="v1.25.0" SWIFT_BRANCH="swift-4.0-release" SWIFT_VERSION="swift-4.0-RELEASE" TAG="aleksaubry/swift-apns:4.0"

install:
    - bash ./.ci/install.sh

script:
    - bash ./.ci/build.sh

deploy:
    provider: script
    script: bash ./.ci/release.sh
    skip_cleanup: true
    on:
        branch: release
